### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by DmitryShapovalov** [omerfarukozturk/UIView-Shimmer#15]
Hello,

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest.
Does UIView-Shimmer need to include this manifest?

Here are some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

**Comment by rishatl** [comment]
As far as I understand, the framework doesn't collect any personal data, so an empty manifest setting should work. Check out the [fix](https://github.com/omerfarukozturk/UIView-Shimmer/pull/16).

**Comment by FlorinDMass** [comment]
Hey @omerfarukozturk ,
Thanks for taking care of the Privacy Manifest you are awesome !
I don't see yet a new version on cocoa pods specs : https://github.com/CocoaPods/Specs/tree/master/Specs/b/8/1/UIView-Shimmer
Are you able to help with this ?
Thanks,
Florin
